server:
  port: 8080
  servlet:
    context-path: /bootcamp

Spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres: // dnpjtrybbrmzww : dbd3299774bcf753957d20ca429c0ea903f8419ce711b464cd45c112f6107bd4 @ ec2-54-167-152-185.compute-1.amazonaws.com : 5432 / d5936vlr8aloci
    username: dnpjtrybbrmzww
    password: dbd3299774bcf753957d20ca429c0ea903f8419ce711b464cd45c112f6107bd4
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none
application:
  description: Projeto criado no Bootcamp DIO - Santander
